name: Extract Commit Patch

on:
  workflow_dispatch:

jobs:
  extract-patch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch source repository
        run: |
          git remote add source https://github.com/ikteach/ginkgo_Kernel.git
          git fetch source

      - name: Generate patch file
        run: |
          # Buat folder khusus buat nyimpen patch
          mkdir -p patches
          # Ekstrak commit jadi file .patch
          git format-patch -1 710270b6babdac2ac33423d7c00d0d5f757231e7 -o patches

      - name: Commit and Push patch
        run: |
          git add patches/
          git commit -m "Add patch file for commit 710270b"
          git push origin HEAD
