name: Cherry-pick Specific Commit

on:
  # Memungkinkan kamu menjalankan workflow secara manual dari tab Actions
  workflow_dispatch:

jobs:
  cherry-pick-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Gunakan PAT agar bisa push ke repo
          token: ${{ secrets.PAT_TOKEN }}
          # Ambil semua history commit agar cherry-pick bisa berjalan
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Add remote source repository
        run: |
          # Tambahkan repo sumber sebagai remote
          git remote add source https://github.com/ikteach/ginkgo_Kernel.git
          # Ambil data terbaru dari repo sumber
          git fetch source

      - name: Cherry-pick the commit
        run: |
          # Lakukan cherry-pick pada commit yang dituju
          git cherry-pick 710270b6babdac2ac33423d7c00d0d5f757231e7

      - name: Push changes
        run: |
          # Push hasil cherry-pick ke branch saat ini di repo fork-mu
          git push origin HEAD